Use urfave/cli for the backport command
rancher/ecm-distro-tools pull request #327
Opened 2024-01-05 09:18 UTC by Tashima42

2024-01-09 11:58 UTC, briandowns requested changes

2024-01-09 11:58 UTC, briandowns commented on repository/repository.go
> +	cherryPick := false
var cherryPick bool

2024-01-09 11:58 UTC, briandowns commented on repository/repository.go
> +func OrgFromRepo(repo string) (string, error) {
Should this be removed again?

2024-01-09 12:17 UTC, briandowns approved these changes

2024-01-11 17:23 UTC, brooksn approved these changes

2024-01-11 17:26 UTC, merged