fix registry urls on generate missing images list
rancher/ecm-distro-tools pull request #467
Opened 2024-08-09 15:14 UTC by tashima42

Problem: The `--registry` flag wasn't working because the registry URL was hardcoded in a function
Solution: Use the registry info to get the correct registry information

2024-08-14 13:15 UTC, briandowns requested changes

2024-08-14 13:15 UTC, briandowns commented on log/log.go
> +func (l Logger) Print(a ...any) (n int, err error) {
We don't use explicit returns anywhere in the code base (or shouldn't if we do) so let's avoid it here as well.

2024-08-14 13:15 UTC, briandowns commented on release/rancher/rancher.go
> +
Kill new line. Keep to 2 sections. Stdlib and third party.

2024-08-14 13:15 UTC, briandowns commented on release/rancher/rancher.go
> +		log.Println("image: " + imageAndVersion)
Library code shouldn't be writing anything. The sapling code of the library should have the freedom to decide what to do with returned error output and calling code or app code should indicate output format.

2024-08-14 13:39 UTC, rafaelbreno approved these changes

2024-08-19 14:21 UTC, rafaelbreno approved these changes

2024-08-19 14:37 UTC, nicholasSUSE approved these changes

2024-08-19 15:04 UTC, briandowns approved these changes

2024-08-19 15:15 UTC, merged